/-
Copyright (c) 2026 Foresight Quantum. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Foresight Quantum
-/
module

public import CQM1.TrotterError.Calculus
public import CQM1.TrotterError.Commutator

import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

/-!
# Commutator expansion of a single conjugation

Single-layer conjugation results for the Trotter error theory (arXiv:1912.08854). This is the
first half of `thm:comm_exp_conj` (theory.tex:137-155): the Taylor expansion of a single
conjugation `e^{τA} X e^{-τA}` of a matrix exponential, before the multi-layer induction.

## Main definitions

* `conj`: the single conjugation `e^{τA} X e^{-τA} = exp (τ • A) * X * exp ((-τ) • A)`.

## Main results

* `conj_hasDerivAt`: `d/dτ conj A X τ = conj A (commutator A X) τ`.
* `conj_sub_eq_integral`: the fundamental-theorem identity
  `conj A X τ - X = ∫₀^τ conj A (commutator A X) s ds`.
* `iteratedDeriv_conj_zero`: `iteratedDeriv j (conj A X) 0 = adPow A j X`.
* `conj_taylor`: the single-layer Taylor expansion with integral remainder (theory.tex:137-150).
* `norm_conj_le`, `norm_conj_remainder_le`: norm bounds for the conjugation and its remainder
  (theory.tex:151-155).

**Assisted by Deepseek Harness**
-/

@[expose] public section

namespace TrotterError

open NormedSpace
open MeasureTheory
open scoped ContDiff algebraMap

/-- Single conjugation `e^{τA} X e^{-τA} = exp (τ • A) * X * exp ((-τ) • A)`. -/
noncomputable def conj {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    (A X : 𝔸) (τ : ℝ) : 𝔸 :=
  exp (τ • A) * X * exp ((-τ) • A)

/-- `A` commutes with `exp (t • A)`, since both live in the commutative-with-`A` subalgebra
generated by `A`. -/
lemma exp_smul_comm {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    (A : 𝔸) (t : ℝ) : Commute A (exp (t • A)) :=
  ((Commute.refl A).smul_right t).exp_right

/-- `t ↦ exp (t • A)` is smooth. -/
lemma contDiff_exp_smul {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A : 𝔸) :
    ContDiff ℝ ∞ (fun t : ℝ => exp (t • A)) := by
  rw [contDiff_iff_contDiffAt]
  intro t
  exact ((NormedSpace.exp_analytic (t • A)).contDiffAt).comp t
    (ContDiffAt.smul (f := fun u : ℝ => u) (g := fun _ : ℝ => A) contDiffAt_id contDiffAt_const)

/-- The conjugation `t ↦ conj A Y t` is smooth. -/
lemma contDiff_conj {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A Y : 𝔸) :
    ContDiff ℝ ∞ (fun t : ℝ => conj A Y t) := by
  unfold conj
  exact ((contDiff_exp_smul A).mul contDiff_const).mul
    ((contDiff_exp_smul A).comp contDiff_neg)

/-- The conjugation `t ↦ conj A Y t` is continuous. -/
lemma continuous_conj {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A Y : 𝔸) :
    Continuous (fun t : ℝ => conj A Y t) :=
  (contDiff_conj A Y).continuous

/-- In an ℝ-algebra, the scalar action `r • a` equals right multiplication `a * (r : 𝔸)`. -/
lemma smul_eq_mul_right {𝔸 : Type*} [Ring 𝔸] [Algebra ℝ 𝔸] (r : ℝ) (a : 𝔸) :
    r • a = a * (r : 𝔸) := by
  rw [Algebra.smul_def, Algebra.commutes]

/-- The Taylor coefficient `(j! : ℝ)⁻¹ * τ^j` acting by `•` equals the paper's form
`(j! : ℝ)⁻¹ • x * (τ : 𝔸)^j`. -/
lemma pow_smul_eq_smul_mul {𝔸 : Type*} [Ring 𝔸] [Algebra ℝ 𝔸] (j : ℕ) (x : 𝔸) (τ : ℝ) :
    ((Nat.factorial j : ℝ)⁻¹ * τ ^ j) • x = (Nat.factorial j : ℝ)⁻¹ • x * (τ : 𝔸) ^ j := by
  rw [mul_smul, smul_eq_mul_right (τ ^ j) x]
  simp

/-- Derivative of the conjugation: `d/dτ conj A X τ = conj A (commutator A X) τ`
(i.e. `e^{τA} [A, X] e^{-τA}`). -/
theorem conj_hasDerivAt {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A X : 𝔸) (τ : ℝ) :
    HasDerivAt (fun s => conj A X s) (conj A (commutator A X) τ) τ := by
  have hneg : HasDerivAt (fun s : ℝ => exp ((-s) • A)) (-A * exp ((-τ) • A)) τ := by
    have h := hasDerivAt_exp_smul_const' (-A) τ
    convert h using 2 <;> simp
  have hmain : HasDerivAt (fun s : ℝ => exp (s • A) * X * exp ((-s) • A))
      (exp (τ • A) * (A * X - X * A) * exp ((-τ) • A)) τ := by
    have h' : HasDerivAt (fun s : ℝ => exp (s • A) * X * exp ((-s) • A))
        (((A * exp (τ • A)) * X) * exp ((-τ) • A) +
          (exp (τ • A) * X) * (-A * exp ((-τ) • A))) τ :=
      (hasDerivAt_exp_smul_const' A τ).mul_const X |>.mul hneg
    convert h' using 1
    noncomm_ring [(exp_smul_comm A τ).eq, (exp_smul_comm A (-τ)).eq]
  simpa [conj, commutator] using hmain

/-- Fundamental theorem of calculus for the conjugation:
`conj A X τ - X = ∫ s in 0..τ, conj A (commutator A X) s`. -/
theorem conj_sub_eq_integral {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A X : 𝔸) (τ : ℝ) :
    conj A X τ - X = ∫ s in 0..τ, conj A (commutator A X) s := by
  have hderiv : ∀ x ∈ Set.uIcc (0 : ℝ) τ,
      HasDerivAt (fun s => conj A X s) (conj A (commutator A X) x) x :=
    fun x _ => conj_hasDerivAt A X x
  have hint : IntervalIntegrable (fun s => conj A (commutator A X) s) volume 0 τ :=
    (continuous_conj A (commutator A X)).intervalIntegrable 0 τ
  have h := intervalIntegral.integral_eq_sub_of_hasDerivAt
    (f := fun s => conj A X s) (f' := fun s => conj A (commutator A X) s)
    (a := 0) (b := τ) hderiv hint
  rw [h]; simp [conj]

/-- The `j`-th iterated derivative of `τ ↦ conj A X τ` is `τ ↦ conj A (adPow A j X) τ`. -/
lemma iteratedDeriv_conj {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A X : 𝔸) (j : ℕ) :
    iteratedDeriv j (fun τ => conj A X τ) = fun τ => conj A (adPow A j X) τ := by
  induction j with
  | zero => simp [iteratedDeriv_zero, adPow]
  | succ j ih =>
      rw [iteratedDeriv_succ, ih]
      funext t
      rw [(conj_hasDerivAt A (adPow A j X) t).deriv]
      rfl

/-- The `j`-th iterated derivative of `τ ↦ conj A X τ` at `0` is `adPow A j X`. -/
theorem iteratedDeriv_conj_zero {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A X : 𝔸) (j : ℕ) :
    iteratedDeriv j (fun τ => conj A X τ) 0 = adPow A j X := by
  rw [iteratedDeriv_conj]; simp [conj]

/-- The standard Taylor remainder integral equals the paper's substituted form:
`∫₀^τ (τ-s)^n/n! • F s = ∫₀^τ F (τ-s) * (s^n/n!)`. -/
lemma integral_smul_eq_integral_mul_sub {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    (F : ℝ → 𝔸) (n : ℕ) (τ : ℝ) :
    (∫ s in 0..τ, ((τ - s) ^ n / (Nat.factorial n : ℝ)) • F s) =
      ∫ s in 0..τ, F (τ - s) * ((s ^ n / (Nat.factorial n : ℝ)) : 𝔸) := by
  calc
    (∫ s in 0..τ, ((τ - s) ^ n / (Nat.factorial n : ℝ)) • F s)
        = ∫ s in 0..τ, F s * (((τ - s) ^ n / (Nat.factorial n : ℝ)) : 𝔸) := by
            apply intervalIntegral.integral_congr_uIoo
            intro s hs
            exact smul_eq_mul_right (((τ - s) ^ n / (Nat.factorial n : ℝ))) (F s)
    _ = ∫ s in 0..τ, F (τ - s) * ((s ^ n / (Nat.factorial n : ℝ)) : 𝔸) := by
            simpa using (intervalIntegral.integral_comp_sub_left (a := 0) (b := τ) (d := τ)
              (f := fun u => F (τ - u) * ((u ^ n / (Nat.factorial n : ℝ)) : 𝔸)))

/-- At `τ = 0`, the Taylor polynomial `∑_{j<p} (j! : ℝ)⁻¹ • (adPow A j X * 0^j)` equals `X`. -/
lemma taylor_poly_zero {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    (A X : 𝔸) (p : ℕ) (hp : 1 ≤ p) :
    (∑ j ∈ Finset.range p, (Nat.factorial j : ℝ)⁻¹ • (adPow A j X * (0 : 𝔸) ^ j)) = X := by
  simpa [adPow] using (Finset.sum_eq_single_of_mem (s := Finset.range p)
    (a := 0) (f := fun j => (Nat.factorial j : ℝ)⁻¹ • (adPow A j X * (0 : 𝔸) ^ j))
    (Finset.mem_range.mpr (lt_of_lt_of_le zero_lt_one hp))
    (by intro b _ hb0; rw [zero_pow hb0, mul_zero, smul_zero]))

/-- `∫₀^τ |s|^(p-1)/(p-1)! ds = |τ|^p/p!` over the unordered interval, for `1 ≤ p`. -/
lemma integral_abs_pow_sub_div_factorial_uIoc (p : ℕ) (τ : ℝ) (hp : 1 ≤ p) :
    (∫ s in Set.uIoc (0 : ℝ) τ, |s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) =
      |τ| ^ p / (Nat.factorial p : ℝ) := by
  have hfac : Nat.factorial p = p * Nat.factorial (p - 1) := by
    simpa [Nat.sub_add_cancel hp] using Nat.factorial_succ (p - 1)
  calc
    (∫ s in Set.uIoc (0 : ℝ) τ, |s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ))
        = (∫ s in Set.uIoc (0 : ℝ) τ, |s| ^ (p - 1)) / (Nat.factorial (p - 1) : ℝ) := by
            rw [MeasureTheory.integral_div]
    _ = (|τ| ^ p / (p : ℝ)) / (Nat.factorial (p - 1) : ℝ) := by
            have hp' : ((p - 1 : ℕ) : ℝ) + 1 = (p : ℝ) := by
              rw [Nat.cast_sub hp]
              ring
            have hpow : (∫ s in Set.uIoc (0 : ℝ) τ, |s| ^ (p - 1)) = |τ| ^ p / (p : ℝ) := by
              have h := integral_pow_abs_sub_uIoc (a := 0) (b := τ) (n := p - 1)
              rw [Nat.sub_add_cancel hp, hp'] at h
              simpa using h
            rw [hpow]
    _ = |τ| ^ p / (Nat.factorial p : ℝ) := by
            rw [hfac, Nat.cast_mul]
            field_simp

/-- `|∫₀^τ |s|^(p-1)/(p-1)! ds| = |τ|^p/p!` for `1 ≤ p`. -/
lemma abs_integral_abs_pow_div_factorial (p : ℕ) (τ : ℝ) (hp : 1 ≤ p) :
    |∫ s in 0..τ, |s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)|
      = |τ| ^ p / (Nat.factorial p : ℝ) := by
  rw [intervalIntegral.abs_integral_eq_abs_integral_uIoc]
  have hnonneg : 0 ≤ (∫ s in Set.uIoc (0 : ℝ) τ, |s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) :=
    MeasureTheory.setIntegral_nonneg measurableSet_uIoc (fun s _ => by positivity)
  rw [abs_of_nonneg hnonneg, integral_abs_pow_sub_div_factorial_uIoc p τ hp]

/-- Single-layer Taylor expansion (theory.tex:137-150):
`conj A X τ = Σ_{j<p} adPow A j X τ^j/j! + ∫₀^τ conj A (adPow A p X) (τ-s) s^{p-1}/(p-1)!`. -/
theorem conj_taylor {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸] (A X : 𝔸) (p : ℕ) (τ : ℝ) (hp : 1 ≤ p) :
    conj A X τ = (∑ j ∈ Finset.range p, (Nat.factorial j : ℝ)⁻¹ • (adPow A j X) * (τ ^ j : 𝔸))
      + ∫ s in 0..τ, conj A (adPow A p X) (τ - s) *
          ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸) := by
  let f : ℝ → 𝔸 := fun s => conj A X s
  let Y : 𝔸 := adPow A p X
  have hf : ContDiff ℝ ∞ f := contDiff_conj A X
  by_cases hτ : τ = 0
  · subst τ
    simp only [conj, zero_smul, neg_zero, exp_zero, one_mul, mul_one,
      intervalIntegral.integral_same, add_zero, smul_mul_assoc, map_zero]
    exact (taylor_poly_zero A X p hp).symm
  · have hud : UniqueDiffOn ℝ (Set.uIcc (0 : ℝ) τ) := uniqueDiffOn_uIcc (Ne.symm hτ)
    have hfOn : ContDiffOn ℝ p f (Set.uIcc (0 : ℝ) τ) :=
      (hf.contDiffOn.mono (Set.subset_univ _)).of_le (mod_cast le_top)
    have hTaylor := taylor_integral_remainder (f := f) (x₀ := 0) (x := τ) (n := p - 1)
      (by simpa [Nat.sub_add_cancel hp] using hfOn)
    rw [Nat.sub_add_cancel hp] at hTaylor
    have hTaylor' : f τ = taylorWithinEval f (p - 1) (Set.uIcc (0 : ℝ) τ) 0 τ
        + ∫ s in 0..τ, ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) •
            iteratedDerivWithin p f (Set.uIcc (0 : ℝ) τ) s := by
      rw [← hTaylor]
      abel
    have hpoly : taylorWithinEval f (p - 1) (Set.uIcc (0 : ℝ) τ) 0 τ
        = ∑ j ∈ Finset.range p, (Nat.factorial j : ℝ)⁻¹ • (adPow A j X) * (τ ^ j : 𝔸) := by
      rw [taylor_within_apply, Nat.sub_add_cancel hp]
      simp only [sub_zero]
      apply Finset.sum_congr rfl
      intro j _
      rw [iteratedDerivWithin_eq_iteratedDeriv hud (hf.contDiffAt.of_le (mod_cast le_top))
        (by simp)]
      rw [iteratedDeriv_conj_zero, pow_smul_eq_smul_mul]
    have hintegral : (∫ s in 0..τ, ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) •
          iteratedDerivWithin p f (Set.uIcc (0 : ℝ) τ) s) =
        ∫ s in 0..τ, conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸) := by
      calc
        (∫ s in 0..τ, ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) •
              iteratedDerivWithin p f (Set.uIcc (0 : ℝ) τ) s)
            = ∫ s in 0..τ, ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) •
                iteratedDeriv p f s := by
                apply intervalIntegral.integral_congr_uIoo
                intro s hs
                change ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) •
                    iteratedDerivWithin p f (Set.uIcc (0 : ℝ) τ) s =
                  ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • iteratedDeriv p f s
                rw [iteratedDerivWithin_eq_iteratedDeriv hud
                  (hf.contDiffAt.of_le (mod_cast le_top)) (Set.uIoo_subset_uIcc_self hs)]
        _ = ∫ s in 0..τ, ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • conj A Y s := by
                apply intervalIntegral.integral_congr_uIoo
                intro s _
                change ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • iteratedDeriv p f s =
                  ((τ - s) ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • conj A Y s
                rw [show iteratedDeriv p f s = conj A Y s by
                  simpa [f, Y] using congr_fun (iteratedDeriv_conj A X p) s]
        _ = ∫ s in 0..τ, conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸) :=
                integral_smul_eq_integral_mul_sub (fun s => conj A Y s) (p - 1) τ
    change f τ = (∑ j ∈ Finset.range p, (Nat.factorial j : ℝ)⁻¹ • (adPow A j X) * (τ ^ j : 𝔸))
      + ∫ s in 0..τ, conj A (adPow A p X) (τ - s) *
          ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸)
    rw [hTaylor', hpoly, hintegral]

/-- The norm of a single conjugation is bounded by `‖Y‖ * exp (2 * |t| * ‖A‖)`. -/
theorem norm_conj_le {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℚ 𝔸] [NormedAlgebra ℝ 𝔸]
    [NormOneClass 𝔸] (A Y : 𝔸) (t : ℝ) :
    ‖conj A Y t‖ ≤ ‖Y‖ * Real.exp (2 * |t| * ‖A‖) := by
  calc
    ‖exp (t • A) * Y * exp ((-t) • A)‖
        ≤ ‖exp (t • A)‖ * ‖Y‖ * ‖exp ((-t) • A)‖ :=
            (norm_mul_le (exp (t • A) * Y) (exp ((-t) • A))).trans
              (mul_le_mul_of_nonneg_right (norm_mul_le (exp (t • A)) Y) (norm_nonneg _))
    _ ≤ Real.exp (|t| * ‖A‖) * ‖Y‖ * Real.exp (|t| * ‖A‖) := by
            have h1 : ‖exp (t • A)‖ ≤ Real.exp (|t| * ‖A‖) := by
              simpa [norm_smul] using norm_exp_le (t • A)
            have h2 : ‖exp ((-t) • A)‖ ≤ Real.exp (|t| * ‖A‖) := by
              simpa [norm_smul] using norm_exp_le ((-t) • A)
            exact mul_le_mul (mul_le_mul h1 (le_refl ‖Y‖) (norm_nonneg _) (by positivity)) h2
              (norm_nonneg _) (by positivity)
    _ = ‖Y‖ * Real.exp (2 * |t| * ‖A‖) := by
            calc
              Real.exp (|t| * ‖A‖) * ‖Y‖ * Real.exp (|t| * ‖A‖)
                  = ‖Y‖ * (Real.exp (|t| * ‖A‖) * Real.exp (|t| * ‖A‖)) := by ring
              _ = ‖Y‖ * Real.exp (|t| * ‖A‖ + |t| * ‖A‖) := by rw [Real.exp_add]
              _ = ‖Y‖ * Real.exp (2 * |t| * ‖A‖) := by ring_nf

/-- Norm bound of the single-layer remainder (theory.tex:151-155):
`‖∫₀^τ conj A (adPow A p X) (τ-s) * s^{p-1}/(p-1)!‖ ≤ ‖adPow A p X‖ * |τ|^p/p! * e^{2|τ|‖A‖}`. -/
theorem norm_conj_remainder_le {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℚ 𝔸]
    [NormedAlgebra ℝ 𝔸] [NormOneClass 𝔸]
    (A X : 𝔸) (p : ℕ) (τ : ℝ) (hp : 1 ≤ p) :
    ‖∫ s in 0..τ, conj A (adPow A p X) (τ - s) *
        ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸)‖
      ≤ ‖adPow A p X‖ * |τ| ^ p / (Nat.factorial p : ℝ) * Real.exp (2 * |τ| * ‖A‖) := by
  let Y : 𝔸 := adPow A p X
  let C : ℝ := ‖Y‖ * Real.exp (2 * |τ| * ‖A‖)
  have hC : 0 ≤ C := mul_nonneg (norm_nonneg Y) (Real.exp_nonneg _)
  have hpoint : ∀ s ∈ Set.uIoc (0 : ℝ) τ,
      ‖conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸)‖
        ≤ C * (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) := by
    intro s hs
    have habs : |τ - s| ≤ |τ| :=
      (by simpa [sub_zero] using Set.abs_sub_right_of_mem_uIcc (Set.uIoc_subset_uIcc hs))
    have hsmul : conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸) =
        (s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • conj A Y (τ - s) :=
      (smul_eq_mul_right (s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) (conj A Y (τ - s))).symm
    have hnormY : ‖conj A Y (τ - s)‖ ≤ ‖Y‖ * Real.exp (2 * |τ| * ‖A‖) := by
      refine (norm_conj_le A Y (τ - s)).trans ?_
      have harg : 2 * |τ - s| * ‖A‖ ≤ 2 * |τ| * ‖A‖ :=
        mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_left habs (by norm_num)) (norm_nonneg A)
      exact mul_le_mul_of_nonneg_left (Real.exp_le_exp.mpr harg) (norm_nonneg Y)
    calc
      ‖conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸)‖
          = ‖(s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) • conj A Y (τ - s)‖ := by rw [hsmul]
      _ = |s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)| * ‖conj A Y (τ - s)‖ := by
            rw [norm_smul, Real.norm_eq_abs]
      _ = (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) * ‖conj A Y (τ - s)‖ := by
            rw [abs_div, abs_pow, abs_of_pos (by positivity : 0 < (Nat.factorial (p - 1) : ℝ))]
      _ ≤ (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) *
            (‖Y‖ * Real.exp (2 * |τ| * ‖A‖)) := by gcongr
      _ = C * (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) := by dsimp [C]; ring
  have hcont_g : Continuous (fun s : ℝ => C * (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ))) := by
    fun_prop
  calc
    ‖∫ s in 0..τ, conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸)‖
        ≤ |∫ s in 0..τ, C * (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ))| := by
            refine intervalIntegral.norm_integral_le_abs_of_norm_le
              (f := fun s => conj A Y (τ - s) * ((s ^ (p - 1) / (Nat.factorial (p - 1) : ℝ)) : 𝔸))
              (g := fun s => C * (|s| ^ (p - 1) / (Nat.factorial (p - 1) : ℝ))) ?_ ?_
            · rw [MeasureTheory.ae_restrict_iff' measurableSet_uIoc]
              filter_upwards with s hs
              exact hpoint s hs
            · exact hcont_g.intervalIntegrable 0 τ
    _ = C * (|τ| ^ p / (Nat.factorial p : ℝ)) := by
            rw [intervalIntegral.integral_const_mul, abs_mul, abs_of_nonneg hC,
              abs_integral_abs_pow_div_factorial p τ hp]
    _ = ‖Y‖ * |τ| ^ p / (Nat.factorial p : ℝ) * Real.exp (2 * |τ| * ‖A‖) := by dsimp [C]; ring

end TrotterError
